# Generated by Django 4.2 on 2024-11-12 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultsabx",
            old_name="indices_miss",
            new_name="first_stim",
        ),
    ]
