# Generated by Django 4.2 on 2024-11-12 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0002_rename_indices_miss_resultsabx_first_stim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultsabx",
            name="CONDITION_ROOT",
        ),
    ]
