# Generated by Django 4.2 on 2024-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0003_remove_resultsabx_condition_root"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultsabx",
            name="task_name",
        ),
    ]
