# Generated by Django 4.2 on 2024-11-12 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0004_remove_resultsabx_task_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_first_adjustment",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_first_measurement",
        ),
    ]
