# Generated by Django 4.2 on 2024-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0005_remove_user_is_first_adjustment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="list_tasks",
            new_name="path_next",
        ),
        migrations.RemoveField(
            model_name="resultsabx",
            name="monitor_size",
        ),
        migrations.RemoveField(
            model_name="user",
            name="measurement_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="practice_completed",
        ),
        migrations.AddField(
            model_name="user",
            name="epsilon_dim_1_plus",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="user",
            name="list_imgs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="path_now",
            field=models.TextField(blank=True),
        ),
    ]
