# Generated by Django 4.2 on 2024-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0006_rename_list_tasks_user_path_next_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="epsilon_dim_1_plus",
            field=models.FloatField(default=1.0),
        ),
    ]
