# Generated by Django 4.2 on 2024-11-13 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0007_alter_user_epsilon_dim_1_plus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="epsilon_dim_1_plus",
        ),
    ]
