# Generated by Django 4.2 on 2024-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0008_remove_user_epsilon_dim_1_plus"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="epsilon_dim_1_plus",
            field=models.IntegerField(default=0.5),
        ),
    ]
