# Generated by Django 4.2 on 2024-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0009_user_epsilon_dim_1_plus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="epsilon_dim_1_plus",
            field=models.FloatField(default=0.5),
        ),
    ]
