# Generated by Django 4.2 on 2024-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abx_app", "0010_alter_user_epsilon_dim_1_plus"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_rep",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="user",
            name="num_per_trial",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="user",
            name="path_img_root",
            field=models.TextField(default="static/abx_app/img/"),
        ),
    ]
