# Generated by Django 4.2 on 2024-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0011_user_max_rep_user_num_per_trial_user_path_img_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='val_rep_ready',
            field=models.IntegerField(default=5),
        ),
    ]
