# Generated by Django 4.2 on 2024-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0012_user_val_rep_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='epsilon_dim_1_plus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_rep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_per_trial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='path_img_root',
        ),
        migrations.RemoveField(
            model_name='user',
            name='val_rep_ready',
        ),
        migrations.AddField(
            model_name='user',
            name='config_exp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='epsilon_dims',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='length_dims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='list_dim_keys',
            field=models.JSONField(default=list),
        ),
    ]
