# Generated by Django 4.2 on 2024-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0013_remove_user_epsilon_dim_1_plus_remove_user_max_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_responses',
            field=models.JSONField(default=list),
        ),
    ]
