# Generated by Django 4.2 on 2024-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0014_user_list_responses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_dim',
            new_name='count_cond',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='length_dims',
            new_name='length_conditions',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='list_dim_keys',
            new_name='list_conditions',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='list_responses',
            new_name='list_conditions_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='epsilon_dims',
        ),
        migrations.AddField(
            model_name='user',
            name='dict_res_responses',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_res_threshold',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_responses_buffer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='list_convergence',
            field=models.JSONField(default=list),
        ),
    ]
