# Generated by Django 4.2 on 2024-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0015_rename_current_dim_user_count_cond_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dict_res_threshold',
            new_name='dict_all_res_responses',
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_res_threshold',
            field=models.JSONField(default=dict),
        ),
    ]
