# Generated by Django 4.2 on 2024-12-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0016_rename_dict_res_threshold_user_dict_all_res_responses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dict_res_responses',
            new_name='dict_res_threshold',
        ),
    ]
