# Generated by Django 4.2 on 2024-12-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0017_rename_dict_res_responses_user_dict_res_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_not_fixate',
            field=models.BooleanField(default=False),
        ),
    ]
