# Generated by Django 4.2 on 2024-12-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0018_user_is_not_fixate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_not_fixate',
            field=models.BooleanField(default=True),
        ),
    ]
