# Generated by Django 4.2 on 2024-12-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0019_alter_user_is_not_fixate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_not_fixate',
        ),
        migrations.AddField(
            model_name='user',
            name='is_fixate',
            field=models.BooleanField(default=False),
        ),
    ]
