# Generated by Django 4.2 on 2024-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0020_remove_user_is_not_fixate_user_is_fixate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dict_all_res_responses',
            new_name='dict_all_res_actual_value',
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_res_convergence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_res_current_stair',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_res_flip_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_sequence_actual_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_sequence_flip',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_sequence_hit',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='dict_all_sequence_threshold',
            field=models.JSONField(default=dict),
        ),
    ]
