# Generated by Django 4.2 on 2024-12-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0021_rename_dict_all_res_responses_user_dict_all_res_actual_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_fixate',
            field=models.BooleanField(default=True),
        ),
    ]
