# Generated by Django 4.2 on 2025-01-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0022_alter_user_is_fixate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='miss_eye_position',
            field=models.IntegerField(default=0),
        ),
    ]
