# Generated by Django 4.2 on 2025-01-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0023_user_miss_eye_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_list_conditions_name_copy',
            field=models.JSONField(default=list),
        ),
    ]
