# Generated by Django 4.2 on 2025-01-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abx_app', '0024_user__list_conditions_name_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dict_responses_buffer',
            new_name='dict_all_responses_buffer',
        ),
    ]
